name: "youtrack-pr-action"
description: "GitHub Actions starter for TypeScript with automated releases"
author: "Koj <https://github.com/koj.co>"
inputs:
  github_token:
    required: true
    description: "GitHub Token"
  token:
    required: true
    description: "YouTrack Token"
  base_url:
    required: true
    description: "YouTrack URL"
  command:
    required: true
    description: "YouTrack Command Query (e.g. 'State Fixed')"
  if:
    required: true
    description: "YouTrack Search Guard (e.g. 'State: Open')"
  base:
    required: false
    description: "Base SHA for manual commits list"
  head:
    required: false
    description: "Head SHA for manual commits list"

runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "move"
  color: "blue"
