name: "Action.ts"
description: "GitHub Actions starter for TypeScript with automated releases"
author: "Koj <https://github.com/koj.co>"
inputs:
  youtrack_token:
    required: true
    description: "YouTrack Token"
  youtrack_base_url:
    required: true
    description: "YouTrack URL"
  github_token:
    required: true
    description: "GitHub Token"
  youtrack_command:
    required: true
    description: "YouTrack Command Query (e.g. 'State Fixed')"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
