name: Build CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Run tests
        run: npm run test
      - uses: JasonEtco/build-and-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
