name: Act Local Run
on:
  push:
    branches:
      - master
jobs:
  local:
    name: Act Local Run
    runs-on: ubuntu-latest
    if: ${{ env.ACT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - uses: ./
        with:
          youtrack_command: State In Progress
          github_token: ${{ secrets.GITHUB_TOKEN }}
          youtrack_token: ${{ secrets.YOUTRACK_TOKEN }}
          youtrack_base_url: ${{ secrets.YOUTRACK_BASE_URL }}
